configName: sam_v71_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_sam_e70_s70_v70_v71;harmony-services;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.5.82\samv71b\atdf\ATSAMV71Q21B.atdf
